### ISSUE TITLE
esp8266 Fatal exception from http_get

### ISSUE THREAD

**Issue by reaper7** [Caerbannog/esphttpclient#1]
I try to execute this request:
`
http_get("http://api.thingspeak.com/update?key=ABCBCACABCBA1234&field1=0&field2=24.0&headers=false", http_callback_example);
`
and from httpclient.c->http_post I got:

```
hostname=api.thingspeak.com
port=80
path=/update?key=ABCBCACABCBA1234&field1=0&field2=24.0&headers=false
```

next executed is: http_raw_request ... req->post_data = esp_strdup(post_data);
give Fatal exception because post_data is NULL

temporary solution are inside static char \* esp_strdup(const char \* str)
add:
`
  if (str == NULL)
    return NULL;
`
with this everything works good

**Comment by Caerbannog** [comment]
You were right.
Fixed in commit 09fdd8e55991c58fedafc770233dce71a6c80ada.
Thank you!
