### ISSUE TITLE
Making PUT requests

### ISSUE THREAD

**Issue by rith87** [Caerbannog/esphttpclient#11]
Anyone working on enabling PUT requests? Or does the ESP somehow not support PUT requests (which seems hard to believe)? If not, I can add some code to handle HTTP PUT.

**Comment by Caerbannog** [comment]
No one is working on it that I know of. I don't see any roadblock.

**Comment by rith87** [comment]
Cool. I have it working on my end and I'll let you take a look as soon as I'm done with some cleanup.
