### ISSUE TITLE
Some sites response with 'HTTP 1.0' and cause 'error'

### ISSUE THREAD

**Issue by MswPaulDSmith** [Caerbannog/esphttpclient#17]
I'm using your library with the 'Weather Underground' API.  This responds with a response claiming to be 'HTTP 1.0' [1] and your library throws an error.  Whilst technically correct this is in the 'yes but it works...' [2] category so you might want to implement something like some options flags, one of which could be HTTP_1_0_RSP_OK.

[1] Confirmed also with Wireshark and making same requests using browsers.
[2] The contents of the response is the word 'success' and the website shows that the the weather status update was accepted.

**Comment by Caerbannog** [comment]
Thanks for pointing that out. This should be fixed in esphttpclient, because the specification alludes to this situation:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.6

**Comment by Caerbannog** [comment]
Thanks for pointing that out. This should be fixed in esphttpclient, because the specification alludes to this situation:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.6

Can you test this commit and report the result?

**Comment by MswPaulDSmith** [comment]
I can but it won't be for a few days as I'm going away over Easter.  However I did take a look and it's exactly the same fix that I made locally to get me going so I'm reasonably confident it will work.

**Comment by Caerbannog** [comment]
@MswPaulDSmith don't hesitate to submit your version if it's any better.

**Comment by Caerbannog** [comment]
This should now be fixed in master.
