### ISSUE TITLE
esp crashes if server doesn't respond

### ISSUE THREAD

**Issue by lukecyca** [Caerbannog/esphttpclient#2]
Thanks for this library! I've used it quite successfully, however I have run into an annoying problem:

I find that if the server I connect to has a valid DNS entry, but is not running an http server, then this library crashes the esp8266 right around `espconn_connect()` inside `dns_callback`.

Is this expected behaviour? I notice there is a `TODO` right at that line to change to using `espconn_regist_reconcb()`. Maybe that's related.

**Comment by lukecyca** [comment]
Amazing! Can't wait to try these improvements out.

**Comment by Caerbannog** [comment]
This was indeed a bug and it should now be fixed. I have tried to handle most failures by calling the callback with a negative status code.
