### ISSUE TITLE
[Feature request] lwIP and mbedTLS port

### ISSUE THREAD

**Issue by flannelhead** [Caerbannog/esphttpclient#28]
Given that there is an open source version of the ESP8266 lwIP port in [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk), I think it would be nice to use that instead of the weird `espconn` interface. `espconn` doesn't seem to add much value upon raw lwIP but rather makes things like connection lifetime somewhat unclear. Usage of the plain lwIP APIs would make this code also more portable to other platforms.

I've looked at it a little bit. For the most part, the transformation looks pretty trivial and would likely even simplify some parts of the code.

The only complicated thing is supporting secure connections. AFAICT `espconn` wraps some TLS library (maybe mbedTLS like in [this example code](http://espressif.com/sites/default/files/sdks/esp8266_nonos_sdk_mbedtls_20160718.zip)) behind the `espconn_secure` API. There the Espressif example code may prove to be helpful.

I'm interested in working on this. However, I'd like to hear your opinion on this. Obviously this change would break the build for users who don't have the `lwIP` headers available in their include path (i.e. not using a recent enough version of `esp-open-sdk`). Users of the library would also have to link against `lwip_open` instead of `lwip`.

Do you think these changes are suitable for the mainline code, or would it be better to indeed fork this library at this point?

Furthermore, I'm interested in taking this library further to the direction of static memory allocation and incremental parsing without buffering the response at all (leaving possible buffering up to the end user), possibly by integrating [http-parser](https://github.com/nodejs/http-parser). Personally I would be inclined to fork the library as these changes would indeed turn the library into an entirely new direction.

**Comment by Caerbannog** [comment]
I suppose that newcomers to the embedded world, and people stumbling on posts explaining esphttpclient will be grateful if the interface does not change that much, and no toolchain settings need to be altered.

But I think that you are probably more qualified than me to make the decision, as I didn't manage to configure lwip the last time I tried. Your arguments seem to be good, so here are the options:

- Publish a v2 release, explain in the README the differences with v1. Maybe explain how to get v1 if you're a newbie.
- Or fork the lib, maybe rename it, and edit the base README to recommend moving to the fork.

**Comment by flannelhead** [comment]
I totally agree with your comment.

Hence, I think forking and renaming is the optimal way to handle this. The fork could be presented as an alternative or a "similar project" as that's what it shall be. Your library is perfectly fine and usable as-is: it supports SSL and can be linked against the official Espressif SDK without any patches.

The fork would be linked against `lwip_open` which is supplied by `esp-open-sdk`. Also, forking gives the freedom to not have feature parity (e.g. not have response buffering in the library, not have SSL/TLS in the beginning).

Does this sound OK to you?

**Comment by Caerbannog** [comment]
Yes :)

**Comment by flannelhead** [comment]
Sadly, I have not had time to work on the matter discussed here, and don't have a need for the planned fork any longer - hence closing this issue.
