### ISSUE TITLE
espconn_gethostbyname issue?

### ISSUE THREAD

**Issue by mwolfeu** [Caerbannog/esphttpclient#8]
I have an SDK which was updated a couple days ago.
Your simple get & simple post examples work fine.
Simple get works great with SSL.

If instead I do an ssl post (which i tested and the site supports)

  http_post("https://httpbin.org/post", "first_word=hello&second_word=world", "Content-Type: application/x-www-form-urlencoded\r\n", http_callback_example);

I get:
DNS pending
http_status=-1

If I manually resolve:
http_post("https://54.175.219.8/post", "first_word=hello&second_word=world", "Content-Type: application/x-www-form-urlencoded\r\n", http_callback_example);

I get:
http_status=-1
ESPCONN_OK, 54.175.219.8, /post, 443, 1

This last line I printed to verify the args.  Everything looks fine.
Can you double check my results?
Thoughts?

Thanks

**Comment by mwolfeu** [comment]
Apparently, the Arduino esp8266 SDK has not been updated to the latest.
When I installed the open SDK and tried  the call there, it worked fine.
Thanks

**Comment by Caerbannog** [comment]
OK, I'm happy that it worked out, and sorry I couldn't investigate earlier :)
