### ISSUE TITLE
Not working with esp8266 v12e

### ISSUE THREAD

**Issue by shyampurk** [Caerbannog/esphttpclient#9]
This library is not working with the latest esp8266 v12e.

Trying to make a simple http_get returns a -1 status.
In case we pass the host name in the URL then DNS always fails.

Has anyone tested it on 8266 12e and succeeded ?

-Shyam

**Comment by Caerbannog** [comment]
I don't have this hardware.
Where you able to make it work? What is your SDK version?

**Comment by by2coffee** [comment]
I was able to make http_post() requests successfully on an ESP-12E (to a URL)

Probably it's more to do with this known issue according to the [tests](https://github.com/Caerbannog/esphttpclient/blob/master/test/httpclient_test.c):

``` C
http_get("http://wtfismyip.com/text", "", http_callback_example);
        // FIXME: this test sometimes fails with "DNS error code -1"
```

**Comment by vowstar** [comment]
I'm using ESP-12E and it works well.
